pub(super) fn flags_for(subcmd: &str, subsub: Option<&str>) -> &'static [&'static str] {
    match (subcmd, subsub) {
        ("ctx", Some("set")) => &[
            "--path",
            "--proxy",
            "--noproxy",
            "-t",
            "--tag",
            "--env",
            "--env-file",
        ],
        ("ctx", Some("list")) | ("ctx", Some("show")) => &["-f", "--format"],
        ("delete", _) | ("del", _) => &[
            "--bookmark",
            "-bm",
            "--reserved",
            "--any",
            "--name",
            "-e",
            "--exclude",
            "-p",
            "--pattern",
            "--no-default-excludes",
            "--no-tui",
            "--dry-run",
            "--what-if",
            "--collect-info",
            "--log",
            "--level",
            "--on-reboot",
            "-y",
            "--yes",
            "-f",
            "--format",
            "--force",
            "--reason",
        ],
        ("list", _) => &[
            "-t",
            "--tag",
            "-s",
            "--sort",
            "-n",
            "--limit",
            "--offset",
            "--reverse",
            "--tsv",
            "-f",
            "--format",
        ],
        ("z", _) | ("open", _) => &["-t", "--tag"],
        ("save", _) | ("set", _) | ("tag", _) => &["-t", "--tag"],
        ("tree", _) => &[
            "-d",
            "--depth",
            "-o",
            "--output",
            "--hidden",
            "--no-clip",
            "--plain",
            "--stats-only",
            "--fast",
            "--sort",
            "--size",
            "--max-items",
            "--include",
            "--exclude",
        ],
        ("redirect", _) => &[
            "--profile",
            "--explain",
            "--stats",
            "--confirm",
            "--review",
            "--log",
            "--tx",
            "--last",
            "--validate",
            "--plan",
            "--apply",
            "--undo",
            "--watch",
            "--status",
            "--simulate",
            "--dry-run",
            "--copy",
            "-y",
            "--yes",
            "-f",
            "--format",
        ],
        ("acl", Some("view")) => &["--path", "-p", "--detail", "--export"],
        ("acl", Some("add")) => &[
            "--path",
            "-p",
            "--file",
            "--paths",
            "--principal",
            "--rights",
            "--ace-type",
            "--inherit",
            "-y",
            "--yes",
        ],
        ("acl", Some("remove")) => &["--path", "-p"],
        ("acl", Some("purge")) => &["--path", "-p", "--principal", "-y", "--yes"],
        ("acl", Some("diff")) => &["--path", "-p", "--reference", "-r", "--output", "-o"],
        ("acl", Some("batch")) => &["--file", "--paths", "--action", "--output", "-y", "--yes"],
        ("acl", Some("effective")) => &["--path", "-p", "--user", "-u"],
        ("acl", Some("copy")) => &["--path", "-p", "--reference", "-r", "-y", "--yes"],
        ("acl", Some("backup")) => &["--path", "-p", "--output", "-o"],
        ("acl", Some("restore")) => &["--path", "-p", "--from", "-y", "--yes"],
        ("acl", Some("inherit")) => &["--path", "-p", "--disable", "--enable", "--preserve"],
        ("acl", Some("owner")) => &["--path", "-p", "--set", "-y", "--yes"],
        ("acl", Some("orphans")) => &[
            "--path",
            "-p",
            "--recursive",
            "--action",
            "--output",
            "-y",
            "--yes",
        ],
        ("acl", Some("repair")) => &["--path", "-p", "--export-errors", "-y", "--yes"],
        ("acl", Some("audit")) => &["--tail", "--export"],
        ("acl", Some("config")) => &["--set"],
        ("export", _) => &["-f", "--format", "-o", "--out"],
        ("import", _) => &[
            "-f", "--format", "-i", "--input", "-m", "--mode", "-y", "--yes",
        ],
        ("env", Some("list")) => &["--scope", "-f", "--format"],
        ("env", Some("search")) => &["--scope", "-f", "--format"],
        ("env", Some("get")) => &["--scope", "-f", "--format"],
        ("env", Some("set")) => &["--scope", "--no-snapshot"],
        ("env", Some("del")) => &["--scope", "-y", "--yes"],
        ("env", Some("check")) => &["--scope", "--fix", "--format"],
        ("env", Some("doctor")) => &["--scope", "--fix", "--format"],
        ("env", Some("path-dedup")) => &["--scope", "--remove-missing", "--dry-run"],
        ("env", Some("profile")) => &["--scope", "-y", "--yes", "-f", "--format"],
        ("env", Some("batch")) => &["--scope", "--dry-run"],
        ("env", Some("apply")) => &["--scope", "-y", "--yes"],
        ("env", Some("export")) => &["--scope", "--format", "--out"],
        ("env", Some("export-live")) => &["--scope", "--format", "--env", "--set", "--out"],
        ("env", Some("env")) => &["--scope", "--format", "--env", "--set"],
        ("env", Some("import")) => &["--scope", "--mode", "--dry-run", "-y", "--yes"],
        ("env", Some("diff-live")) => &["--scope", "--snapshot", "--color", "--format"],
        ("env", Some("template")) => &["--scope", "--validate-only", "--format"],
        ("env", Some("run")) => &[
            "--env",
            "--set",
            "--scope",
            "--shell",
            "--schema-check",
            "--notify",
        ],
        ("env", Some("validate")) => &["--scope", "--format", "--strict"],
        ("env", Some("schema")) => &["--format", "--warn-only", "-y", "--yes"],
        ("env", Some("annotate")) => &["--format"],
        ("env", Some("config")) => &["--format", "-y", "--yes"],
        ("env", Some("audit")) => &["--limit", "--format"],
        ("env", Some("watch")) => &["--scope", "--interval-ms", "--format", "--once"],
        _ => &[],
    }
}
