import type {
  TaskFieldType,
  TaskFieldValue,
  TaskFormState,
  TaskFieldOption,
  TaskFieldDefinition,
  TaskNoticeTone,
  TaskNotice,
  WorkspaceTaskDefinition,
  WorkspaceTaskGroup,
  WorkspaceTabDefinition
} from './catalog-shared'

import {
  JSON_FORMAT,
  desktopWindowNotices,
  desktopHostsNotices,
  desktopColorNotices,
  shellInitOptions,
  shellCompletionOptions,
  aliasTypeOptions,
  aliasModeOptions,
  aliasShellOptions,
  dedupModeOptions,
  brnCaseOptions,
  imgFormatOptions,
  imgSvgMethodOptions,
  imgJpegBackendOptions,
  aliasAppScanSourceOptions,
  videoModeOptions,
  videoEngineOptions,
  aclRightsOptions,
  aclAceTypeOptions,
  aclInheritOptions,
  aclInheritModeOptions,
  readText,
  readBool,
  splitItems,
  splitCommand,
  pushOption,
  pushRepeatableOption,
  runTask,
  guardedTask,
  pathTarget,
  previewPath,
  moveLikeArgs
} from './catalog-shared'

export const pathsContextTaskGroups: WorkspaceTaskGroup[] = [
  {
    id: 'ctx-core',
    title: '上下文控制',
    description: '基于 ctx 子命令管理本地上下文配置。',
    tasks: [
      runTask({
        id: 'ctx-list',
        workspace: 'paths-context',
        title: '列出上下文',
        description: '查看已定义的上下文配置。',
        action: 'ctx:list',
        fields: [],
        buildRunArgs: () => ['ctx', 'list', '-f', JSON_FORMAT],
      }),
      runTask({
        id: 'ctx-show',
        workspace: 'paths-context',
        title: '查看上下文',
        description: '查看指定上下文或当前激活上下文。',
        action: 'ctx:show',
        fields: [{ key: 'name', label: '配置名', type: 'text', placeholder: '留空则查看当前激活上下文' }],
        target: (values) => readText(values, 'name'),
        buildRunArgs: (values) => {
          const name = readText(values, 'name')
          return ['ctx', 'show', ...(name ? [name] : []), '-f', JSON_FORMAT]
        },
      }),
      runTask({
        id: 'ctx-use',
        workspace: 'paths-context',
        title: '启用上下文',
        description: '切换到目标上下文。',
        action: 'ctx:use',
        fields: [{ key: 'name', label: '配置名', type: 'text', required: true, placeholder: '例如 work' }],
        target: (values) => readText(values, 'name'),
        buildRunArgs: (values) => ['ctx', 'use', readText(values, 'name')],
      }),
      runTask({
        id: 'ctx-off',
        workspace: 'paths-context',
        title: '停用上下文',
        description: '清除当前激活上下文。',
        action: 'ctx:off',
        fields: [],
        buildRunArgs: () => ['ctx', 'off'],
      }),
      runTask({
        id: 'ctx-set',
        workspace: 'paths-context',
        title: '写入上下文',
        description: '定义或更新上下文配置。环境变量支持逗号或换行分隔。',
        action: 'ctx:set',
        fields: [
          { key: 'name', label: '配置名', type: 'text', required: true, placeholder: '例如 work' },
          { key: 'path', label: '工作目录', type: 'text', placeholder: 'D:/repo/project' },
          { key: 'proxy', label: '代理', type: 'text', placeholder: 'http://127.0.0.1:7890 | off | keep' },
          { key: 'noproxy', label: 'NO_PROXY', type: 'text', placeholder: 'localhost,127.0.0.1' },
          { key: 'tag', label: '默认标签', type: 'text', placeholder: 'work,repo' },
          { key: 'env', label: '环境变量', type: 'textarea', placeholder: 'KEY=VALUE' },
          { key: 'envFile', label: 'env 文件', type: 'text', placeholder: '.env.local' },
        ],
        target: (values) => readText(values, 'name'),
        buildRunArgs: (values) => {
          const args = ['ctx', 'set', readText(values, 'name')]
          pushOption(args, '--path', readText(values, 'path'))
          pushOption(args, '--proxy', readText(values, 'proxy'))
          pushOption(args, '--noproxy', readText(values, 'noproxy'))
          pushOption(args, '-t', readText(values, 'tag'))
          pushRepeatableOption(args, '--env', readText(values, 'env'))
          pushOption(args, '--env-file', readText(values, 'envFile'))
          return args
        },
      }),
      guardedTask({
        id: 'ctx-del',
        workspace: 'paths-context',
        title: '删除上下文',
        description: '删除指定上下文，先预览详情再确认。',
        action: 'ctx:del',
        tone: 'danger',
        fields: [{ key: 'name', label: '配置名', type: 'text', required: true, placeholder: '例如 work' }],
        target: (values) => readText(values, 'name'),
        buildPreviewArgs: (values) => ['ctx', 'show', readText(values, 'name'), '-f', JSON_FORMAT],
        buildExecuteArgs: (values) => ['ctx', 'del', readText(values, 'name')],
        previewSummary: (values) => `删除上下文 ${readText(values, 'name')}`,
      }),
      runTask({
        id: 'ctx-rename',
        workspace: 'paths-context',
        title: '重命名上下文',
        description: '重命名现有上下文配置。',
        action: 'ctx:rename',
        fields: [
          { key: 'old', label: '旧名称', type: 'text', required: true },
          { key: 'next', label: '新名称', type: 'text', required: true },
        ],
        target: (values) => `${readText(values, 'old')} -> ${readText(values, 'next')}`,
        buildRunArgs: (values) => ['ctx', 'rename', readText(values, 'old'), readText(values, 'next')],
      }),
    ],
  },
  {
    id: 'bookmark-health',
    title: '书签与健康',
    description: '补齐 recent / stats / check / gc / dedup 等维护能力。',
    tasks: [
      runTask({
        id: 'recent',
        workspace: 'paths-context',
        title: '最近访问',
        description: '查看最近访问的书签。',
        action: 'recent',
        fields: [
          { key: 'limit', label: '数量', type: 'number', defaultValue: '10', min: 1 },
          { key: 'tag', label: '标签过滤', type: 'text', placeholder: '可选' },
        ],
        buildRunArgs: (values) => {
          const args = ['recent', '-n', readText(values, 'limit') || '10', '-f', JSON_FORMAT]
          pushOption(args, '-t', readText(values, 'tag'))
          return args
        },
      }),
      runTask({
        id: 'bookmark-stats',
        workspace: 'paths-context',
        title: '书签统计',
        description: '查看书签统计摘要。',
        action: 'stats',
        fields: [],
        buildRunArgs: () => ['stats', '-f', JSON_FORMAT],
      }),
      runTask({
        id: 'bookmark-check',
        workspace: 'paths-context',
        title: '健康检查',
        description: '检查缺失路径、重复项和陈旧记录。',
        action: 'check',
        fields: [{ key: 'days', label: '陈旧阈值(天)', type: 'number', defaultValue: '90', min: 1 }],
        buildRunArgs: (values) => ['check', '-d', readText(values, 'days') || '90', '-f', JSON_FORMAT],
      }),
      runTask({
        id: 'gc-preview',
        workspace: 'paths-context',
        title: '扫描死链',
        description: '预览死链书签，不做删除。',
        action: 'gc:preview',
        fields: [],
        buildRunArgs: () => ['gc', '-f', JSON_FORMAT],
      }),
      guardedTask({
        id: 'gc-purge',
        workspace: 'paths-context',
        title: '清理死链',
        description: '先预览后清理所有死链书签。',
        action: 'gc:purge',
        tone: 'danger',
        fields: [],
        target: () => 'dead-links',
        buildPreviewArgs: () => ['gc', '-f', JSON_FORMAT],
        buildExecuteArgs: () => ['gc', '--purge', '-f', JSON_FORMAT],
        previewSummary: () => '清理全部死链书签',
      }),
      guardedTask({
        id: 'dedup',
        workspace: 'paths-context',
        title: '去重书签',
        description: '按路径或名称做去重，先看统计再执行。',
        action: 'dedup',
        tone: 'danger',
        fields: [{ key: 'mode', label: '模式', type: 'select', defaultValue: 'path', options: dedupModeOptions }],
        target: (values) => `mode=${readText(values, 'mode') || 'path'}`,
        buildPreviewArgs: () => ['stats', '-f', JSON_FORMAT],
        buildExecuteArgs: (values) => ['dedup', '-m', readText(values, 'mode') || 'path', '-f', JSON_FORMAT, '-y'],
        previewSummary: (values) => `执行书签去重：${readText(values, 'mode') || 'path'}`,
      }),
    ],
  },
  {
    id: 'bookmark-query',
    title: '路径检索',
    description: '以 CLI 机器输出形式接入 keys / all / fuzzy / ws。',
    tasks: [
      runTask({
        id: 'keys',
        workspace: 'paths-context',
        title: '键列表',
        description: '输出所有书签键。',
        action: 'keys',
        fields: [],
        buildRunArgs: () => ['keys'],
      }),
      runTask({
        id: 'all',
        workspace: 'paths-context',
        title: '全部书签',
        description: '按标签输出全部书签。',
        action: 'all',
        fields: [{ key: 'tag', label: '标签', type: 'text', placeholder: '可选' }],
        buildRunArgs: (values) => ['all', ...(readText(values, 'tag') ? [readText(values, 'tag')] : [])],
      }),
      runTask({
        id: 'fuzzy',
        workspace: 'paths-context',
        title: '模糊匹配',
        description: '按模式做机器可读搜索。',
        action: 'fuzzy',
        fields: [
          { key: 'pattern', label: '模式', type: 'text', required: true, placeholder: '例如 doc' },
          { key: 'tag', label: '标签', type: 'text', placeholder: '可选' },
        ],
        target: (values) => readText(values, 'pattern'),
        buildRunArgs: (values) => ['fuzzy', readText(values, 'pattern'), ...(readText(values, 'tag') ? [readText(values, 'tag')] : [])],
      }),
      runTask({
        id: 'ws',
        workspace: 'paths-context',
        title: '工作区批量打开（ws）',
        description: '按标签在 Windows Terminal 中批量打开路径（ws）。',
        action: 'ws',
        fields: [{ key: 'tag', label: '标签', type: 'text', required: true, placeholder: '例如 work' }],
        target: (values) => readText(values, 'tag'),
        buildRunArgs: (values) => ['ws', readText(values, 'tag')],
      }),
    ],
  },
]
