#[cfg(feature = "desktop")]
pub(crate) mod apps;
#[cfg(feature = "desktop")]
pub(crate) mod awake;
#[cfg(feature = "desktop")]
pub(crate) mod color;
#[cfg(feature = "desktop")]
pub(crate) mod daemon;
#[cfg(feature = "desktop")]
pub(crate) mod hosts;
#[cfg(feature = "desktop")]
pub(crate) mod hotkey;
#[cfg(feature = "desktop")]
pub(crate) mod layout;
#[cfg(feature = "desktop")]
pub(crate) mod remap;
#[cfg(feature = "desktop")]
pub(crate) mod shell;
#[cfg(feature = "desktop")]
pub(crate) mod snippet;
#[cfg(feature = "desktop")]
pub(crate) mod theme;
#[cfg(feature = "desktop")]
pub(crate) mod window;
