use std::collections::HashMap;

use super::super::types::{EnvError, EnvResult, EnvScope, EnvVar, ExportFormat};

pub(super) fn export_vars(
    vars: &[EnvVar],
    scope: EnvScope,
    format: ExportFormat,
) -> EnvResult<String> {
    match format {
        ExportFormat::Json => export_json(vars, scope),
        ExportFormat::Env => Ok(export_env(vars)),
        ExportFormat::Reg => Ok(export_reg(vars, scope)),
        ExportFormat::Csv => export_csv(vars),
    }
}

fn export_json(vars: &[EnvVar], scope: EnvScope) -> EnvResult<String> {
    let map: HashMap<&str, &str> = vars
        .iter()
        .map(|v| (v.name.as_str(), v.raw_value.as_str()))
        .collect();
    let wrapper = serde_json::json!({
        "scope": scope,
        "vars": map,
    });
    Ok(serde_json::to_string_pretty(&wrapper)?)
}

fn export_env(vars: &[EnvVar]) -> String {
    let mut lines = vec!["# Generated by xun env export".to_string(), String::new()];
    for v in vars {
        if v.raw_value.contains(' ') {
            lines.push(format!(
                "{}=\"{}\"",
                v.name,
                v.raw_value.replace('"', "\\\"")
            ));
        } else {
            lines.push(format!("{}={}", v.name, v.raw_value));
        }
    }
    lines.join("\n")
}

fn export_reg(vars: &[EnvVar], scope: EnvScope) -> String {
    let key = match scope {
        EnvScope::User => "HKEY_CURRENT_USER\\Environment",
        EnvScope::System => {
            "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Environment"
        }
        EnvScope::All => "HKEY_CURRENT_USER\\Environment",
    };
    let mut lines = vec![
        "Windows Registry Editor Version 5.00".to_string(),
        String::new(),
        format!("[{}]", key),
    ];
    for v in vars {
        if v.reg_type == 2 {
            let hex: Vec<String> = v
                .raw_value
                .encode_utf16()
                .chain(std::iter::once(0))
                .flat_map(|u| u.to_le_bytes())
                .map(|b| format!("{:02x}", b))
                .collect();
            lines.push(format!("\"{}\"=hex(2):{}", v.name, hex.join(",")));
        } else {
            lines.push(format!(
                "\"{}\"=\"{}\"",
                v.name,
                v.raw_value.replace('\\', "\\\\").replace('"', "\\\"")
            ));
        }
    }
    lines.join("\n")
}

fn export_csv(vars: &[EnvVar]) -> EnvResult<String> {
    let mut writer = csv::Writer::from_writer(Vec::<u8>::new());
    writer.write_record(["name", "value", "reg_type", "scope"])?;
    for var in vars {
        writer.write_record([
            var.name.as_str(),
            var.raw_value.as_str(),
            &var.reg_type.to_string(),
            &var.scope.to_string(),
        ])?;
    }
    let data = writer
        .into_inner()
        .map_err(|e| EnvError::Io(e.into_error()))?;
    String::from_utf8(data).map_err(|e| EnvError::Other(format!("utf8 conversion failed: {}", e)))
}

pub(super) fn export_ext(format: ExportFormat) -> &'static str {
    match format {
        ExportFormat::Json => "json",
        ExportFormat::Env => "env",
        ExportFormat::Reg => "reg",
        ExportFormat::Csv => "csv",
    }
}
